version: "3"

services:
  app:
    build: .
    ports:
      - 3040:3040
    environment:
      - MONGODB_URI=mongodb://mongo:27017/blog_db
      - POSTGRES_URI=postgresql://will:postgres@postgres:5432/blog
      - PORT=3040
      - SECRET=390842p7uyfkluhpsaiofpuyg20983yr3o2puhrf32
    depends_on:
      - postgres
      - mongo

  postgres:
    image: postgres:12
    environment:
      - POSTGRES_USER=will
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=blog
    volumes:
      - ./init:/docker-entrypoint-initdb.d
      - postgres-data:/var/lib/postgresql/data

  mongo:
    image: mongo:4.4
    volumes:
      - mongo-data:/data/db

volumes:
  postgres-data:
  mongo-data:
