DELETE  http://localhost:3040/api/blogs/66003ceae215cee3c1c40784
Content-Type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IndpbGwiLCJpZCI6IjY2MDAzY2M5ZTIxNWNlZTNjMWM0MDc4MCIsImlhdCI6MTcxMTI5MTYwNiwiZXhwIjoxNzExMjk1MjA2fQ.J07LySQ9bjKxKGG_Arj3wN7zrig4IMMW6fI-lQiqoZw
