POST http://localhost:3040/api/blogs
Content-Type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IndpbGwiLCJpZCI6IjljZDg5NTQ0LTY4ZDMtNDM0MS05ZTM5LTk2NDM3NDIwMWVhNyIsImlhdCI6MTcxMjYwNzk4MywiZXhwIjoxNzEyNjExNTgzfQ.BdUls17tjEpl_IaquGp36ssXfwHjmF4CzTCDUUtX-2E

{
  "title": "Thnings I don't know yet",
  "author": "Dan Abramov",
  "url": "www.sample.com",
  "likes": 3
}